# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'klui03.ui'
##
## Created by: Qt User Interface Compiler version 6.3.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QLabel,
    QMainWindow, QPushButton, QSizePolicy, QStackedWidget,
    QWidget)
# import test_rc

class Ui_kluiUI(object):
    def setupUi(self, kluiUI):
        if not kluiUI.objectName():
            kluiUI.setObjectName(u"kluiUI")
        kluiUI.resize(1080, 720)
        self.centralwidget = QWidget(kluiUI)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(180, 0, 900, 720))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.stackedWidget = QStackedWidget(self.frame)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, 0, 900, 720))
        self.stackedWidget.setStyleSheet(u"background-color: rgb(222, 222, 222);")
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.label_4 = QLabel(self.page)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(720, 600, 161, 20))
        self.label_4.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.frame_2 = QFrame(self.page)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(0, 0, 900, 80))
        self.frame_2.setStyleSheet(u"background-color: rgb(100, 100, 100);")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.label_8 = QLabel(self.frame_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(40, 0, 151, 80))
        self.label_8.setStyleSheet(u"font: 25pt \"Courier\";\n"
"color: rgb(255, 255, 255);")
        self.label_8.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_9 = QLabel(self.frame_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(569, 0, 281, 80))
        self.label_9.setStyleSheet(u"font: 25pt \"Courier\";\n"
"color: rgb(255, 255, 255);")
        self.label_9.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.pushButton_7 = QPushButton(self.page)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(50, 330, 201, 70))
        self.pushButton_7.setStyleSheet(u"font: 20pt \"Courier\";\n"
"background-color: rgb(210, 210, 210);")
        self.pushButton_8 = QPushButton(self.page)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(50, 470, 201, 70))
        self.pushButton_8.setStyleSheet(u"font: 20pt \"Courier\";\n"
"background-color: rgb(50, 50, 50);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_9 = QPushButton(self.page)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(50, 550, 201, 70))
        self.pushButton_9.setStyleSheet(u"font: 20pt \"Courier\";\n"
"background-color: rgb(245, 245, 245);")
        self.checkBox = QCheckBox(self.page)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(50, 200, 221, 16))
        self.checkBox.setStyleSheet(u"font: 10pt \"Courier\";")
        self.checkBox.setTristate(False)
        self.checkBox_2 = QCheckBox(self.page)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(50, 230, 221, 16))
        self.checkBox_2.setStyleSheet(u"font: 10pt \"Courier\";")
        self.checkBox_3 = QCheckBox(self.page)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setGeometry(QRect(50, 260, 221, 16))
        self.checkBox_3.setStyleSheet(u"font: 10pt \"Courier\";")
        self.frame_3 = QFrame(self.page)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(340, 110, 480, 480))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.label_10 = QLabel(self.frame_3)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(0, 0, 60, 60))
        self.label_10.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_10.setScaledContents(True)
        self.label_11 = QLabel(self.frame_3)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(60, 0, 60, 60))
        self.label_11.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_11.setScaledContents(True)
        self.label_12 = QLabel(self.frame_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(120, 0, 60, 60))
        self.label_12.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_12.setScaledContents(True)
        self.label_13 = QLabel(self.frame_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(180, 0, 60, 60))
        self.label_13.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_13.setScaledContents(True)
        self.label_14 = QLabel(self.frame_3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(240, 0, 60, 60))
        self.label_14.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_14.setScaledContents(True)
        self.label_15 = QLabel(self.frame_3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(300, 0, 60, 60))
        self.label_15.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_15.setScaledContents(True)
        self.label_16 = QLabel(self.frame_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(360, 0, 60, 60))
        self.label_16.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_16.setScaledContents(True)
        self.label_17 = QLabel(self.frame_3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(420, 0, 60, 60))
        self.label_17.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_17.setScaledContents(True)
        self.label_18 = QLabel(self.frame_3)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(0, 60, 60, 60))
        self.label_18.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_18.setScaledContents(True)
        self.label_19 = QLabel(self.frame_3)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(180, 60, 60, 60))
        self.label_19.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_19.setScaledContents(True)
        self.label_20 = QLabel(self.frame_3)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(300, 60, 60, 60))
        self.label_20.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_20.setScaledContents(True)
        self.label_21 = QLabel(self.frame_3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(420, 60, 60, 60))
        self.label_21.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_21.setScaledContents(True)
        self.label_22 = QLabel(self.frame_3)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(60, 60, 60, 60))
        self.label_22.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_22.setScaledContents(True)
        self.label_23 = QLabel(self.frame_3)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(360, 60, 60, 60))
        self.label_23.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_23.setScaledContents(True)
        self.label_24 = QLabel(self.frame_3)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(120, 60, 60, 60))
        self.label_24.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_24.setScaledContents(True)
        self.label_25 = QLabel(self.frame_3)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(240, 60, 60, 60))
        self.label_25.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_25.setScaledContents(True)
        self.label_26 = QLabel(self.frame_3)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(120, 120, 60, 60))
        self.label_26.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_26.setScaledContents(True)
        self.label_27 = QLabel(self.frame_3)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(240, 120, 60, 60))
        self.label_27.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_27.setScaledContents(True)
        self.label_28 = QLabel(self.frame_3)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(360, 120, 60, 60))
        self.label_28.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_28.setScaledContents(True)
        self.label_29 = QLabel(self.frame_3)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(0, 120, 60, 60))
        self.label_29.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_29.setScaledContents(True)
        self.label_30 = QLabel(self.frame_3)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(300, 120, 60, 60))
        self.label_30.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_30.setScaledContents(True)
        self.label_31 = QLabel(self.frame_3)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(420, 120, 60, 60))
        self.label_31.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_31.setScaledContents(True)
        self.label_32 = QLabel(self.frame_3)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(0, 180, 60, 60))
        self.label_32.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_32.setScaledContents(True)
        self.label_33 = QLabel(self.frame_3)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(120, 180, 60, 60))
        self.label_33.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_33.setScaledContents(True)
        self.label_34 = QLabel(self.frame_3)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(60, 180, 60, 60))
        self.label_34.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_34.setScaledContents(True)
        self.label_35 = QLabel(self.frame_3)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(360, 180, 60, 60))
        self.label_35.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_35.setScaledContents(True)
        self.label_36 = QLabel(self.frame_3)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(240, 180, 60, 60))
        self.label_36.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_36.setScaledContents(True)
        self.label_37 = QLabel(self.frame_3)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(300, 180, 60, 60))
        self.label_37.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_37.setScaledContents(True)
        self.label_38 = QLabel(self.frame_3)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(420, 180, 60, 60))
        self.label_38.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_38.setScaledContents(True)
        self.label_39 = QLabel(self.frame_3)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(60, 120, 60, 60))
        self.label_39.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_39.setScaledContents(True)
        self.label_40 = QLabel(self.frame_3)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(180, 120, 60, 60))
        self.label_40.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_40.setScaledContents(True)
        self.label_41 = QLabel(self.frame_3)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(180, 180, 60, 60))
        self.label_41.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_41.setScaledContents(True)
        self.label_42 = QLabel(self.frame_3)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(120, 240, 60, 60))
        self.label_42.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_42.setScaledContents(True)
        self.label_43 = QLabel(self.frame_3)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(240, 240, 60, 60))
        self.label_43.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_43.setScaledContents(True)
        self.label_44 = QLabel(self.frame_3)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(360, 240, 60, 60))
        self.label_44.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_44.setScaledContents(True)
        self.label_45 = QLabel(self.frame_3)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(0, 240, 60, 60))
        self.label_45.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_45.setScaledContents(True)
        self.label_46 = QLabel(self.frame_3)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(300, 240, 60, 60))
        self.label_46.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_46.setScaledContents(True)
        self.label_47 = QLabel(self.frame_3)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(420, 240, 60, 60))
        self.label_47.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_47.setScaledContents(True)
        self.label_48 = QLabel(self.frame_3)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(0, 300, 60, 60))
        self.label_48.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_48.setScaledContents(True)
        self.label_49 = QLabel(self.frame_3)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(120, 300, 60, 60))
        self.label_49.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_49.setScaledContents(True)
        self.label_50 = QLabel(self.frame_3)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(60, 300, 60, 60))
        self.label_50.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_50.setScaledContents(True)
        self.label_51 = QLabel(self.frame_3)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(360, 300, 60, 60))
        self.label_51.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_51.setScaledContents(True)
        self.label_52 = QLabel(self.frame_3)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(240, 300, 60, 60))
        self.label_52.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_52.setScaledContents(True)
        self.label_53 = QLabel(self.frame_3)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(300, 300, 60, 60))
        self.label_53.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_53.setScaledContents(True)
        self.label_54 = QLabel(self.frame_3)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(420, 300, 60, 60))
        self.label_54.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_54.setScaledContents(True)
        self.label_55 = QLabel(self.frame_3)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(60, 240, 60, 60))
        self.label_55.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_55.setScaledContents(True)
        self.label_56 = QLabel(self.frame_3)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(180, 240, 60, 60))
        self.label_56.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_56.setScaledContents(True)
        self.label_57 = QLabel(self.frame_3)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(180, 300, 60, 60))
        self.label_57.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_57.setScaledContents(True)
        self.label_58 = QLabel(self.frame_3)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(120, 360, 60, 60))
        self.label_58.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_58.setScaledContents(True)
        self.label_59 = QLabel(self.frame_3)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(240, 360, 60, 60))
        self.label_59.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_59.setScaledContents(True)
        self.label_60 = QLabel(self.frame_3)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(360, 360, 60, 60))
        self.label_60.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_60.setScaledContents(True)
        self.label_61 = QLabel(self.frame_3)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(0, 360, 60, 60))
        self.label_61.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_61.setScaledContents(True)
        self.label_62 = QLabel(self.frame_3)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(300, 360, 60, 60))
        self.label_62.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_62.setScaledContents(True)
        self.label_63 = QLabel(self.frame_3)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(420, 360, 60, 60))
        self.label_63.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_63.setScaledContents(True)
        self.label_64 = QLabel(self.frame_3)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(0, 420, 60, 60))
        self.label_64.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_64.setScaledContents(True)
        self.label_65 = QLabel(self.frame_3)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(120, 420, 60, 60))
        self.label_65.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_65.setScaledContents(True)
        self.label_66 = QLabel(self.frame_3)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setGeometry(QRect(60, 420, 60, 60))
        self.label_66.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_66.setScaledContents(True)
        self.label_67 = QLabel(self.frame_3)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setGeometry(QRect(360, 420, 60, 60))
        self.label_67.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_67.setScaledContents(True)
        self.label_68 = QLabel(self.frame_3)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setGeometry(QRect(240, 420, 60, 60))
        self.label_68.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_68.setScaledContents(True)
        self.label_69 = QLabel(self.frame_3)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setGeometry(QRect(300, 420, 60, 60))
        self.label_69.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_69.setScaledContents(True)
        self.label_70 = QLabel(self.frame_3)
        self.label_70.setObjectName(u"label_70")
        self.label_70.setGeometry(QRect(420, 420, 60, 60))
        self.label_70.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_70.setScaledContents(True)
        self.label_71 = QLabel(self.frame_3)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setGeometry(QRect(60, 360, 60, 60))
        self.label_71.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_71.setScaledContents(True)
        self.label_72 = QLabel(self.frame_3)
        self.label_72.setObjectName(u"label_72")
        self.label_72.setGeometry(QRect(180, 360, 60, 60))
        self.label_72.setStyleSheet(u"background-color: rgb(153, 153, 153);")
        self.label_72.setScaledContents(True)
        self.label_73 = QLabel(self.frame_3)
        self.label_73.setObjectName(u"label_73")
        self.label_73.setGeometry(QRect(180, 420, 60, 60))
        self.label_73.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_73.setScaledContents(True)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.label_5 = QLabel(self.page_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(370, 100, 47, 14))
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.label_6 = QLabel(self.page_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(420, 130, 47, 14))
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.label_7 = QLabel(self.page_4)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(440, 140, 47, 14))
        self.stackedWidget.addWidget(self.page_4)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 100, 141, 181))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet(u"image: url(:/newPrefix/robot.png);")
        self.label.setPixmap(QPixmap(u":/newPrefix/image-klui/robot.png"))
        self.label.setScaledContents(True)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 20, 161, 31))
        self.label_2.setStyleSheet(u"font: 75 15pt \"Courier\";\n"
"color: rgb(11, 0, 178);")
        self.label_2.setTextFormat(Qt.RichText)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_2.setWordWrap(False)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 50, 161, 31))
        self.label_3.setStyleSheet(u"font: 75 15pt \"Courier\";\n"
"color: rgb(209, 115, 0);")
        self.label_3.setTextFormat(Qt.RichText)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_3.setWordWrap(False)
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(0, 330, 180, 50))
        self.pushButton.setMouseTracking(False)
        self.pushButton.setStyleSheet(u"font: 10pt \"Courier\";\n"
"background-color: rgb(230, 230, 230);")
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(0, 380, 180, 50))
        self.pushButton_2.setStyleSheet(u"font: 10pt \"Courier\";")
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(0, 430, 180, 50))
        self.pushButton_3.setMouseTracking(False)
        self.pushButton_3.setStyleSheet(u"font: 10pt \"Courier\";\n"
"background-color: rgb(230, 230, 230);")
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(0, 480, 180, 50))
        self.pushButton_4.setStyleSheet(u"font: 10pt \"Courier\";")
        self.pushButton_5 = QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(0, 530, 180, 50))
        self.pushButton_5.setMouseTracking(False)
        self.pushButton_5.setStyleSheet(u"font: 10pt \"Courier\";\n"
"background-color: rgb(230, 230, 230);")
        self.pushButton_6 = QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(0, 580, 180, 50))
        self.pushButton_6.setStyleSheet(u"font: 10pt \"Courier\";")
        kluiUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(kluiUI)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(kluiUI)
    # setupUi

    def retranslateUi(self, kluiUI):
        kluiUI.setWindowTitle(QCoreApplication.translate("kluiUI", u"LnwmoduleUI", None))
        self.label_4.setText(QCoreApplication.translate("kluiUI", u"full chess game page", None))
        self.label_8.setText(QCoreApplication.translate("kluiUI", u"00:00", None))
        self.label_9.setText(QCoreApplication.translate("kluiUI", u"Move Status", None))
        self.pushButton_7.setText(QCoreApplication.translate("kluiUI", u"Game Start", None))
        self.pushButton_8.setText(QCoreApplication.translate("kluiUI", u"Black Move", None))
        self.pushButton_9.setText(QCoreApplication.translate("kluiUI", u"White Move", None))
        self.checkBox.setText(QCoreApplication.translate("kluiUI", u"Player White ,AI Black", None))
        self.checkBox_2.setText(QCoreApplication.translate("kluiUI", u"AI White ,Player Black", None))
        self.checkBox_3.setText(QCoreApplication.translate("kluiUI", u"Player All (debug)", None))
        self.label_10.setText("")
        self.label_11.setText("")
        self.label_12.setText("")
        self.label_13.setText("")
        self.label_14.setText("")
        self.label_15.setText("")
        self.label_16.setText("")
        self.label_17.setText("")
        self.label_18.setText("")
        self.label_19.setText("")
        self.label_20.setText("")
        self.label_21.setText("")
        self.label_22.setText("")
        self.label_23.setText("")
        self.label_24.setText("")
        self.label_25.setText("")
        self.label_26.setText("")
        self.label_27.setText("")
        self.label_28.setText("")
        self.label_29.setText("")
        self.label_30.setText("")
        self.label_31.setText("")
        self.label_32.setText("")
        self.label_33.setText("")
        self.label_34.setText("")
        self.label_35.setText("")
        self.label_36.setText("")
        self.label_37.setText("")
        self.label_38.setText("")
        self.label_39.setText("")
        self.label_40.setText("")
        self.label_41.setText("")
        self.label_42.setText("")
        self.label_43.setText("")
        self.label_44.setText("")
        self.label_45.setText("")
        self.label_46.setText("")
        self.label_47.setText("")
        self.label_48.setText("")
        self.label_49.setText("")
        self.label_50.setText("")
        self.label_51.setText("")
        self.label_52.setText("")
        self.label_53.setText("")
        self.label_54.setText("")
        self.label_55.setText("")
        self.label_56.setText("")
        self.label_57.setText("")
        self.label_58.setText("")
        self.label_59.setText("")
        self.label_60.setText("")
        self.label_61.setText("")
        self.label_62.setText("")
        self.label_63.setText("")
        self.label_64.setText("")
        self.label_65.setText("")
        self.label_66.setText("")
        self.label_67.setText("")
        self.label_68.setText("")
        self.label_69.setText("")
        self.label_70.setText("")
        self.label_71.setText("")
        self.label_72.setText("")
        self.label_73.setText("")
        self.label_5.setText(QCoreApplication.translate("kluiUI", u"PAGE 2", None))
        self.label_6.setText(QCoreApplication.translate("kluiUI", u"PAGE 3", None))
        self.label_7.setText(QCoreApplication.translate("kluiUI", u"PAGE 4", None))
        self.label.setText("")
        self.label_2.setText(QCoreApplication.translate("kluiUI", u"LnwModule 8-9", None))
        self.label_3.setText(QCoreApplication.translate("kluiUI", u"FIBO", None))
        self.pushButton.setText(QCoreApplication.translate("kluiUI", u"Full Chess Game", None))
        self.pushButton_2.setText(QCoreApplication.translate("kluiUI", u"Manual Chess Game", None))
        self.pushButton_3.setText(QCoreApplication.translate("kluiUI", u"Robot Jog", None))
        self.pushButton_4.setText(QCoreApplication.translate("kluiUI", u"Robot Move", None))
        self.pushButton_5.setText(QCoreApplication.translate("kluiUI", u"Sethome", None))
        self.pushButton_6.setText(QCoreApplication.translate("kluiUI", u"Contact", None))
    # retranslateUi

