# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\klui\Desktop\3_2\module89\return\klui-return\kluiUI\test_klui\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_kluiUI(object):
    def setupUi(self, kluiUI):
        kluiUI.setObjectName("kluiUI")
        kluiUI.resize(1080, 720)
        self.centralwidget = QtWidgets.QWidget(kluiUI)
        self.centralwidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(180, 0, 900, 720))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 900, 720))
        self.stackedWidget.setStyleSheet("background-color: rgb(222, 222, 222);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(390, 80, 47, 14))
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setGeometry(QtCore.QRect(370, 100, 47, 14))
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_6 = QtWidgets.QLabel(self.page_3)
        self.label_6.setGeometry(QtCore.QRect(420, 130, 47, 14))
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_7 = QtWidgets.QLabel(self.page_4)
        self.label_7.setGeometry(QtCore.QRect(440, 140, 47, 14))
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.page_4)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 100, 141, 181))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("image: url(:/newPrefix/robot.png);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/robot.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 161, 31))
        self.label_2.setStyleSheet("font: 75 15pt \"Courier\";")
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 161, 31))
        self.label_3.setStyleSheet("font: 75 15pt \"Courier\";")
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 330, 180, 50))
        self.pushButton.setStyleSheet("font: 10pt \"Courier\";\n"
"background-color: rgb(230, 230, 230);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 380, 180, 50))
        self.pushButton_2.setStyleSheet("font: 10pt \"Courier\";")
        self.pushButton_2.setObjectName("pushButton_2")
        kluiUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(kluiUI)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(kluiUI)

    def retranslateUi(self, kluiUI):
        _translate = QtCore.QCoreApplication.translate
        kluiUI.setWindowTitle(_translate("kluiUI", "LnwmoduleUI"))
        self.label_4.setText(_translate("kluiUI", "PAGE 1"))
        self.label_5.setText(_translate("kluiUI", "PAGE 2"))
        self.label_6.setText(_translate("kluiUI", "PAGE 3"))
        self.label_7.setText(_translate("kluiUI", "PAGE 4"))
        self.label_2.setText(_translate("kluiUI", "LnwModule 8-9"))
        self.label_3.setText(_translate("kluiUI", "FIBO"))
        self.pushButton.setText(_translate("kluiUI", "Chess Game"))
        self.pushButton_2.setText(_translate("kluiUI", "Jog"))
# import test_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    kluiUI = QtWidgets.QMainWindow()
    ui = Ui_kluiUI()
    ui.setupUi(kluiUI)
    kluiUI.show()
    sys.exit(app.exec_())
